// Generated by gencpp from file turtle_cmd/ControlCommand.msg
// DO NOT EDIT!


#ifndef TURTLE_CMD_MESSAGE_CONTROLCOMMAND_H
#define TURTLE_CMD_MESSAGE_CONTROLCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace turtle_cmd
{
template <class ContainerAllocator>
struct ControlCommand_
{
  typedef ControlCommand_<ContainerAllocator> Type;

  ControlCommand_()
    : header()
    , throttle()
    , steering_angle()  {
    }
  ControlCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , throttle(_alloc)
    , steering_angle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _throttle_type;
  _throttle_type throttle;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _steering_angle_type;
  _steering_angle_type steering_angle;





  typedef boost::shared_ptr< ::turtle_cmd::ControlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_cmd::ControlCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCommand_

typedef ::turtle_cmd::ControlCommand_<std::allocator<void> > ControlCommand;

typedef boost::shared_ptr< ::turtle_cmd::ControlCommand > ControlCommandPtr;
typedef boost::shared_ptr< ::turtle_cmd::ControlCommand const> ControlCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_cmd::ControlCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_cmd::ControlCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_cmd::ControlCommand_<ContainerAllocator1> & lhs, const ::turtle_cmd::ControlCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.throttle == rhs.throttle &&
    lhs.steering_angle == rhs.steering_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_cmd::ControlCommand_<ContainerAllocator1> & lhs, const ::turtle_cmd::ControlCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_cmd

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_cmd::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_cmd::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_cmd::ControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_cmd::ControlCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_cmd::ControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_cmd::ControlCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_cmd::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fca5f8768fc3871e4f1d86aed4bfd13f";
  }

  static const char* value(const ::turtle_cmd::ControlCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfca5f8768fc3871eULL;
  static const uint64_t static_value2 = 0x4f1d86aed4bfd13fULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_cmd::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_cmd/ControlCommand";
  }

  static const char* value(const ::turtle_cmd::ControlCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_cmd::ControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"std_msgs/Float32 throttle        # Throttle value between [-1, 1]\n"
"std_msgs/Float32 steering_angle  # Steering angle value between [-1, 1], where left < 0, right > 0\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::turtle_cmd::ControlCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_cmd::ControlCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.throttle);
      stream.next(m.steering_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_cmd::ControlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_cmd::ControlCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "throttle: ";
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.throttle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_angle: ";
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.steering_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CMD_MESSAGE_CONTROLCOMMAND_H
