// Generated by gencpp from file turtle_cmd/InsDelta.msg
// DO NOT EDIT!


#ifndef TURTLE_CMD_MESSAGE_INSDELTA_H
#define TURTLE_CMD_MESSAGE_INSDELTA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace turtle_cmd
{
template <class ContainerAllocator>
struct InsDelta_
{
  typedef InsDelta_<ContainerAllocator> Type;

  InsDelta_()
    : header()
    , total_omega_(0.0)
    , total_distance_x_(0.0)
    , total_distance_y_(0.0)  {
    }
  InsDelta_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , total_omega_(0.0)
    , total_distance_x_(0.0)
    , total_distance_y_(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _total_omega__type;
  _total_omega__type total_omega_;

   typedef float _total_distance_x__type;
  _total_distance_x__type total_distance_x_;

   typedef float _total_distance_y__type;
  _total_distance_y__type total_distance_y_;





  typedef boost::shared_ptr< ::turtle_cmd::InsDelta_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_cmd::InsDelta_<ContainerAllocator> const> ConstPtr;

}; // struct InsDelta_

typedef ::turtle_cmd::InsDelta_<std::allocator<void> > InsDelta;

typedef boost::shared_ptr< ::turtle_cmd::InsDelta > InsDeltaPtr;
typedef boost::shared_ptr< ::turtle_cmd::InsDelta const> InsDeltaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_cmd::InsDelta_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_cmd::InsDelta_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_cmd::InsDelta_<ContainerAllocator1> & lhs, const ::turtle_cmd::InsDelta_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.total_omega_ == rhs.total_omega_ &&
    lhs.total_distance_x_ == rhs.total_distance_x_ &&
    lhs.total_distance_y_ == rhs.total_distance_y_;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_cmd::InsDelta_<ContainerAllocator1> & lhs, const ::turtle_cmd::InsDelta_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_cmd

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_cmd::InsDelta_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_cmd::InsDelta_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_cmd::InsDelta_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_cmd::InsDelta_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_cmd::InsDelta_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_cmd::InsDelta_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_cmd::InsDelta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78be272aef4772d93c7dec5f93e56fdd";
  }

  static const char* value(const ::turtle_cmd::InsDelta_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78be272aef4772d9ULL;
  static const uint64_t static_value2 = 0x3c7dec5f93e56fddULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_cmd::InsDelta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_cmd/InsDelta";
  }

  static const char* value(const ::turtle_cmd::InsDelta_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_cmd::InsDelta_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32 total_omega_\n"
"float32 total_distance_x_\n"
"float32 total_distance_y_\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::turtle_cmd::InsDelta_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_cmd::InsDelta_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.total_omega_);
      stream.next(m.total_distance_x_);
      stream.next(m.total_distance_y_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InsDelta_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_cmd::InsDelta_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_cmd::InsDelta_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_omega_: ";
    Printer<float>::stream(s, indent + "  ", v.total_omega_);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_distance_x_: ";
    Printer<float>::stream(s, indent + "  ", v.total_distance_x_);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_distance_y_: ";
    Printer<float>::stream(s, indent + "  ", v.total_distance_y_);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CMD_MESSAGE_INSDELTA_H
