// Generated by gencpp from file turtle_cmd/TurtleVel.msg
// DO NOT EDIT!


#ifndef TURTLE_CMD_MESSAGE_TURTLEVEL_H
#define TURTLE_CMD_MESSAGE_TURTLEVEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_cmd
{
template <class ContainerAllocator>
struct TurtleVel_
{
  typedef TurtleVel_<ContainerAllocator> Type;

  TurtleVel_()
    : linear(0.0)
    , angular(0.0)  {
    }
  TurtleVel_(const ContainerAllocator& _alloc)
    : linear(0.0)
    , angular(0.0)  {
  (void)_alloc;
    }



   typedef float _linear_type;
  _linear_type linear;

   typedef float _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::turtle_cmd::TurtleVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_cmd::TurtleVel_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleVel_

typedef ::turtle_cmd::TurtleVel_<std::allocator<void> > TurtleVel;

typedef boost::shared_ptr< ::turtle_cmd::TurtleVel > TurtleVelPtr;
typedef boost::shared_ptr< ::turtle_cmd::TurtleVel const> TurtleVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_cmd::TurtleVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_cmd::TurtleVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_cmd::TurtleVel_<ContainerAllocator1> & lhs, const ::turtle_cmd::TurtleVel_<ContainerAllocator2> & rhs)
{
  return lhs.linear == rhs.linear &&
    lhs.angular == rhs.angular;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_cmd::TurtleVel_<ContainerAllocator1> & lhs, const ::turtle_cmd::TurtleVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_cmd

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_cmd::TurtleVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_cmd::TurtleVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_cmd::TurtleVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_cmd::TurtleVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_cmd::TurtleVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_cmd::TurtleVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_cmd::TurtleVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const ::turtle_cmd::TurtleVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d5c2dcd348ac8f7ULL;
  static const uint64_t static_value2 = 0x6ce2a4307bd63a13ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_cmd::TurtleVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_cmd/TurtleVel";
  }

  static const char* value(const ::turtle_cmd::TurtleVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_cmd::TurtleVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 linear\n"
"float32 angular\n"
;
  }

  static const char* value(const ::turtle_cmd::TurtleVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_cmd::TurtleVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_cmd::TurtleVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_cmd::TurtleVel_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "linear: ";
    Printer<float>::stream(s, indent + "  ", v.linear);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CMD_MESSAGE_TURTLEVEL_H
